
server:
  port: 8080


spring:
  redis:
    database: 0
    host: localhost
    port: 6379
  #    host: 8.137.53.199
#    username: default
#    password: 123456
  application:
    name: r-pan-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sync_pan?characterEncoding=utf8&serverTimeZone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 使用数据库自增id
      id-type: auto


storage:
  type: local # 可选 local/ali_oss/fastdfs
  local:
    root-path: C:/Users/23825/Desktop/毕业设计/测试/single
    root-chunk-path: C:/Users/23825/Desktop/毕业设计/测试/chunk


#oss:
#    endpoint: oss-cn-hangzhou.aliyuncs.com
#    access-key: your-access-key
#    secret-key: your-secret-key
#    bucket-name: pan-bucket

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#        exclude: env,beans
logging:
  level:
    root: INFO