
server:
  port: 8080


spring:
  redis:
    database: 0
    host: localhost
    port: 6379
  #    host: 8.137.53.199
#    username: default
#    password: 123456
  application:
    name: r-pan-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 2382546457@qq.com
    #授权码
    password: vjlbzmychvnxebfb
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sync_pan?characterEncoding=utf8&serverTimeZone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 使用数据库自增id
      id-type: auto


storage:
  type: local # 可选 local/ali_oss/fastdfs
  local:
    root-path: /Users/kikihhe/sync-pan/file/single
    root-chunk-path: /Users/kikihhe/sync-pan/file/chunk


#oss:
#    endpoint: oss-cn-hangzhou.aliyuncs.com
#    access-key: your-access-key
#    secret-key: your-secret-key
#    bucket-name: pan-bucket

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#        exclude: env,beans
logging:
  level:
    root: INFO