name: Deploy server

on:
  push:
    branches:
      - main
      - master


jobs:
  build-and-deploy:
    name: 构建并发布
    runs-on: centos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup jdk version
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      # 生成 WAR/JAR 文件
      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t image-name .

      - name: 将docker镜像打包为tar文件
        run: docker save -o image-name.tar image-name

      - name: 将 tar 文件上传至服务器
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "image-name.tar"
          target: "/tmp/your-image-name.tar"


      - name: 加载 docker 镜像并运行
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker load -i /tmp/image-name.tar
            docker stop container-name || true
            docker rm container-name || true
            docker run -d --name container-name -p 8080:80 image-name